#!/bin/bash

# Options are: hmod, runecraft

DIRECTORY="/usr/local/mcwebmin/minecraft/"
cd $DIRECTORY

if [ ! -e "minecraft_server.jar" ]
then
    wget http://minecraft.net/download/minecraft_server.jar
else
    echo "It exists, moving on"
fi


if [ "$1" = "hmod" ]; then

	# Download Hey0 Mod
	if [ ! -e "hmod.zip" ]
	then
	    wget -O hmod.zip http://hey0.net/get.php?dl=serverbeta
	else
	    echo "It exists, moving on"
	fi


	unzip hmod.zip -d hmod/

	# Adds hmod to minecraft_server.jar
	/etc/init.d/minecraft stop
	echo "Server stopped"
	unzip hmod/bin/Minecraft_Mod.jar -d hmodjar/
	cd hmodjar/
	rm -r Main.class META-INF/
	jar uvf ../minecraft_server.jar ./*
	cd ..


	# Update manifest - not sure if needed, must test
	jar umf hmod_manifest minecraft_server.jar
	
	# Create plugins dir
	mkdir plugins/
	#Start the server
	/etc/init.d/minecraft start
	echo "Server stopped"
	# Clean up
	rm -r hmod/ hmodjar/ hmod.zip

	echo "Finished"
fi

if [ "$1" = "runecraft" ]; then

	#Download runecraft
	if [ ! -e "runecraft_latest.zip" ]
	then
	    wget http://llama.cerberusstudios.net/runecraft_latest.zip
	else
	    echo "It exists, moving on"
	fi

	# Unzips runecraft to a directory
	unzip runecraft_latest.zip -d runecraft/

	#Stop server
	/etc/init.d/minecraft stop
	echo "Server stopped"

	# Adds all of the files to the minecraft jar
	cd runecraft/
	jar uvf ../minecraft_server.jar ./*
	cd ..

	#Start server
	/etc/init.d/minecraft start
	echo "Server started"

	# Cleans up
	rm -r runecraft/ runecraft_latest.zip

	echo "Finished"
fi

