#!/bin/bash
#Bash based editor
#Help: vkues ##sed
#Version 0.2

#Path to the MCWebmin/minecraft instalation
MCWDIR="/usr/local/mcwebmin/minecraft"

cd $MCWDIR

if [ "$1" = "edit" ]; then

	SEARCHSTRING=$3
	RESULT=$4
	FILE=$2

	sed -i 's|^$SEARCHSTRING=.*|$SEARCHSTRING=$RESULT|' $FILE

elif [ "$1" = "add" ]; then
	echo $3 >> $MCWDIR/$2
elif [ "$1" = "new" ]; then
	echo $3 > $MCWDIR/$2
elif [ "$1" = "remove" ]; then

	SEARCHSTRING=$3
	FILE=$2

	sed -i '|$SEARCHSTRING|d' $FILE

else
	echo "Syntax: editor edit/add/remove/new file string1 string2"
	echo "File path is relative to the MCWebmin path + /minecraft"
fi

exit
